dir: ./.hypercloud
brandname: Hypercloud
hostname: hypercloud.local
port: 8080
ui: hypercloud-ui-vanilla
sites: false
rateLimiting: true
defaultDiskUsageLimit: 100mb

# processing jobs
jobs:
  popularArchivesIndex: 30s
  userDiskUsage: 5m

# user settings
registration:
  open: false
  allowed:
    - alice@mail.com
    - bob@mail.com
  reservedNames:
    - admin
    - root
    - support
    - noreply
    - users
    - archives
admin:
  email: ''
  password: ''

# email settings
email:
  transport: stub
  sender: '"Hypercloud" <noreply@hypercloud.local>'

# login sessions
sessions:
  algorithm: HS256
  secret: THIS MUST BE REPLACED!
  expiresIn: 1h

# lets encrypt
letsencrypt:
  debug: true
  configDir: ./.letsencrypt