dir: ./.hashbase
brandname: Hashbase
hostname: hashbase.local
port: 8080
letsencrypt: false
sites: false
rateLimiting: true
defaultDiskUsageLimit: 100mb
pm2: false

# processing jobs
jobs:
  popularArchivesIndex: 30s
  userDiskUsage: 5m
  deleteDeadArchives: 5m

# user settings
registration:
  open: false
  allowed:
    - alice@mail.com
    - bob@mail.com
  reservedNames:
    - admin
    - root
    - support
    - noreply
    - users
    - archives
admin:
  email: ''
  password: ''

# email settings
email:
  transport: stub
  sender: '"Hashbase" <noreply@hashbase.local>'

# login sessions
sessions:
  algorithm: HS256
  secret: THIS MUST BE REPLACED!
  expiresIn: 1h