dir: ./.hypercloud
hostname: hypercloud.local
port: 8080
admin:
  email: ''
  password: ''
email:
  transport: stub
  sender: '"Hypercloud" <noreply@hypercloud.local>'
sessions:
  secret: THIS MUST BE REPLACED!
  expiresIn: 1h
proofs:
  secret: THIS MUST BE REPLACED!